sudo: false
language: node_js
node_js:
    - "node"
cache:
    directories:
        - "node_modules"
env:
    - FX_VERSION="54.0b"
    - FX_VERSION="45.0.2esr"
matrix:
    fast_finish: true
    #allow_failures:
    #    - env: FX_CHANNEL="beta"
notifications:
    email: false
install:
    - if [ $FX_VERSION = "45.0.2esr" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/releases/45.0.2esr/linux-x86_64/en-US/firefox-45.0.2esr.tar.bz2";
      fi
    - if [ $FX_VERSION = "54.0b" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-beta-linux64-add-on-devel/1496339244/firefox-54.0.en-US.linux-x86_64-add-on-devel.tar.bz2";
      fi
    - tar xf tarball
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm i
    - node_modules/.bin/gulp build
script:
    - test/runtests.sh -x firefox/firefox
